### ISSUE TITLE
Order of operations

### ISSUE THREAD

**Issue by maltaisn** [maltaisn/calcdialoglib#1]
Would be a good thing to have one day.

**Comment by pk-fr** [comment]
+1 ....

btw, I had to call getSupportFragmentManager() instead of getFragmentManager() in the show method...

and a little rendering enhancement to have a good feedback: when clicking on "ok" without clicking on "=" before,  it would be nice to have the result displayed, and a small delay of 100ms after the closing and returning the result

**Comment by maltaisn** [comment]
I have no plan on adding an option to enable the order of operations for now, but you can try implementing it yourself and sending a PR.

Also, you're supposed to use `getSupportFragmentManager()` because the dialog extends from the appcompat dialog (android.app.Fragment is deprecated) I changed it in the wiki.

Can you open a separate issue for the ok button enhancement?

**Comment by Guiorgy** [comment]
@maltaisn , I might try to do that. Though please don't expect anything, I am just experimenting right now...

**Comment by maltaisn** [comment]
I gave up on the idea because it would probably require parenthesis buttons and there's hardly any space for them. Also I don't think most users expect a simple calculator dialog to have such complexity, I prefer to keep it simple.

You can try implementing it but I probably won't add it to the library.

**Comment by Guiorgy** [comment]
so I made some room for it...

![scientific](https://user-images.githubusercontent.com/27736965/47578389-5324ba00-d95a-11e8-8ef2-0ae787d0389e.png)

PS. the arrow up (↑) is shift, whitch swaps the top operation buttons and reveals even more...

**Comment by maltaisn** [comment]
That's great but I feel like it goes beyond the purpose of a simple calculator, meant to slightly enhance the numeric keyboard.

I do encourage you to release your own library if you wish but I don't plan on merging the changes.

**Comment by maltaisn** [comment]
This was added in v2.0.0
