### ISSUE TITLE
Callback not called on fragment

### ISSUE THREAD

**Issue by doniwinata** [maltaisn/calcdialoglib#11]
Hi i am trying to get the callback from a fragment, but the onValueEntered never called.
Is there any way to  make it works on fragment ? either set callback manually or make it works from fragment. Let me know if you need further information. Thank you in advance

**Comment by doniwinata** [comment]
Sorry seems like i need to pass childfragment manager then it works, sorry for wrong report. thanks

**Comment by maltaisn** [comment]
Yes that's right you need to pass the child FragmentManager or use `setTargetFragment` on the dialog.
