### ISSUE TITLE
isAnwerButtonShown does not work

### ISSUE THREAD

**Issue by guger** [maltaisn/calcdialoglib#17]
```
CalcDialog().apply {
    settings.apply {
        initialValue = value
        isSignBtnShown = false
        isAnswerBtnShown = false
    }
}.show(childFragmentManager, null)
```

This code shows the equal/answer button.

**Comment by maltaisn** [comment]
Are you sure you're not calling it anywhere else? It's weird because not only the answer button is hidden by default but it also works in the demo app, with nothing more than using the setter like you do.

**Comment by guger** [comment]
Well, the error was in my code! Thanks!
