### ISSUE TITLE
android-maven-gradle-plugin was abandoned

### ISSUE THREAD

**Issue by Guiorgy** [maltaisn/calcdialoglib#19]
> I've stopped doing android development yeard ago, and gradle making constant changes to their build system made supporting that plugin quite hard for me.
If you are using Kotlin 1.3.30+ and Gradle 5.x, please use https://github.com/sky-uk/gradle-maven-plugin instead.

It wasn't maintained since early 2018, but officially anounced (in the README) this Jun.

**Comment by maltaisn** [comment]
Thanks I will look into it for the next release.

**Comment by Guiorgy** [comment]
https://developer.android.com/studio/build/maven-publish-plugin
