### ISSUE TITLE
Reusing answer

### ISSUE THREAD

**Issue by maltaisn** [maltaisn/calcdialoglib#2]
If I do 2 + 2 = 5, and then I want to find 1 / 5 without re-entering the past answer
If no number is entered after operation button click and then equal button is pressed, make calculation using past answer. Would need a way to make it evident to the user, like replacing the `=` by `ANS` and replacing it back when a number is entered.

**Comment by maltaisn** [comment]
Added in v1.1

**Comment by Guiorgy** [comment]
is this still a thing?

**Comment by maltaisn** [comment]
Yes, you can show the answer button with `setShowAnswerButton(boolean show)`.
