### ISSUE TITLE
Use as keyboard

### ISSUE THREAD

**Issue by c0dehunter** [maltaisn/calcdialoglib#23]
Is it possible to use this as a keyboard instead of dialog? I have a screen with dynamically updated values, and would like to be able to input number on the fly and see changes.

Like this:

![image](https://user-images.githubusercontent.com/1484658/70018114-06c99600-15c0-11ea-9166-c9ae3afebe98.png)

**Comment by maltaisn** [comment]
Sorry for the late reply. No, this is not possible. Keyboards are actually complete separate apps, not just a fragment. What you could do is take the code from the library, put the dialog view into a fragment, and show this fragment when user focus is on your text fields.
