### ISSUE TITLE
Request feature: Simple clear

### ISSUE THREAD

**Issue by webserveis** [maltaisn/calcdialoglib#3]
to simplify the action delete everything:
Add long touch to erase everything or short touch to erase last digit

**Comment by maltaisn** [comment]
There's a clear button as the neutral button of the dialog, it resets everything. The display will show `0`, but you can use `setShowZeroWhenNoValue(true)` to display nothing.

**Comment by maltaisn** [comment]
I misread what you wanted. I added this in v1.1 as an attribute to `CalcEraseButton` view.

You can do something like this in your app's `styles.xml`:
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="calcDialogStyle">@style/CustomCalcDialogStyle</item>
</style>

<style name="CustomCalcDialogStyle" parent="CalcDialogStyle">
    <item name="calcEraseBtnStyle">@style/CustomCalcEraseBtnStyle</item>
</style>

<style name="CustomCalcEraseBtnStyle" parent="CalcEraseBtnStyle">
    <item name="calcEraseAllOnHold">true</item>
    <item name="calcEraseHoldDelay">1500</item>  <!-- Long touch delay -->
</style>
```
