### ISSUE TITLE
onValueEntered does not return on CalcDialog.CalcDialogCallback inside a Custom View

### ISSUE THREAD

**Issue by a2ke5e1** [maltaisn/calcdialoglib#32]
I am trying to add Dialog Box inside my custom view but When I press ok button dialog boc but does return any value

Here is the code

`class FeaturedEditTextView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyle: Int = 0,
    defStyleRes: Int = 0
) : LinearLayout(context, attrs, defStyle, defStyleRes) , CalcDialog.CalcDialogCallback {

  
    var text: String = ""
        get() = try {
            ScientificNumber.SNumber(field.toDouble(), p).toDouble()
                .toString()
        } catch (ex: NumberFormatException) {
            "0.0"
        }
        set(value) {
            field = value
        }

    var hint: String = ""
        get() = field
        set(value) {
            field = value
            updateHint(value)
        }

    private fun updateHint(value: String) {
        text_holder.setHint(value)
    }

    init {
        LayoutInflater.from(context)
            .inflate(R.layout.featued_edit_text_view, this, true)

        if (attrs != null) {
            val math = context.obtainStyledAttributes(attrs, R.styleable.FeaturedEditTextView)

            if (math.hasValue(R.styleable.FeaturedEditTextView_text)) {
                text = math.getString(R.styleable.FeaturedEditTextView_text).toString()
                textView.setText(text)
            }
            if (math.hasValue(R.styleable.FeaturedEditTextView_hintText)) {
                hint = math.getString(R.styleable.FeaturedEditTextView_hintText).toString()
                updateHint(hint)
            }

            math.recycle()

         

          

            calc_btn.setOnClickListener {
                val calcDialog = CalcDialog()
                calcDialog.getSettings().setInitialValue(text.toBigDecimal())
                calcDialog.settings.requestCode = 1
                calcDialog.settings.isExpressionShown = true
                calcDialog.show(getFragmentManager(context)!!, "calc_dialog")
            }

        }

        textView.doAfterTextChanged {
            text = textView.text.toString()
        }
    }

    private fun getFragmentManager(context: Context?): FragmentManager? {
        return when (context) {
            is AppCompatActivity -> context.supportFragmentManager
            is Fragment -> context.childFragmentManager
            is ContextThemeWrapper -> getFragmentManager(context.baseContext)
            else -> null
        }
    }

    override fun onValueEntered(requestCode: Int, value: BigDecimal?) {
       if (requestCode == 1) {
           Toast.makeText(context, value.toString(), Toast.LENGTH_SHORT).show()
       }
    }

}`

**Comment by a2ke5e1** [comment]
i though i fixed but does not work 
`class FeaturedEditTextView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyle: Int = 0,
    defStyleRes: Int = 0
) : LinearLayout(context, attrs, defStyle, defStyleRes) , CalcDialog.CalcDialogCallback {


    var p = 0.0
    var unit: Map<String, Double> = mapOf(
        "m" to 0.0,
        "µm" to -6.0,
    )
        get() = field
        set(value) {
            updateUnit(value)
        }

    var text: String = ""
        get() = try {
            ScientificNumber.SNumber(field.toDouble(), p).toDouble()
                .toString()
        } catch (ex: NumberFormatException) {
            "0.0"
        }
        set(value) {
            field = value
        }

    var hint: String = ""
        get() = field
        set(value) {
            field = value
            updateHint(value)
        }

    private fun updateHint(value: String) {
        text_holder.setHint(value)
    }




    init {
        LayoutInflater.from(context)
            .inflate(R.layout.featued_edit_text_view, this, true)

        if (attrs != null) {
            val math = context.obtainStyledAttributes(attrs, R.styleable.FeaturedEditTextView)

            if (math.hasValue(R.styleable.FeaturedEditTextView_text)) {
                text = math.getString(R.styleable.FeaturedEditTextView_text).toString()
                textView.setText(text)
            }
            if (math.hasValue(R.styleable.FeaturedEditTextView_hintText)) {
                hint = math.getString(R.styleable.FeaturedEditTextView_hintText).toString()
                updateHint(hint)
            }

            math.recycle()

            updateUnit(unit)


            sqrt_chip.setOnClickListener {
                try {
                    val x = sqrt(textView.text.toString().toDouble())
                    textView.setText(x.toString())
                } catch (ex: NumberFormatException) {

                }
            }
            cubrt_chip.setOnClickListener {
                try {
                    val x = Math.pow(textView.text.toString().toDouble(), 1.0 / 3)
                    textView.setText(x.format(5).toString())
                } catch (ex: NumberFormatException) {

                }
            }


            calc_btn.setOnClickListener {
                val calcDialog = CalcDialog()
                calcDialog.getSettings().setInitialValue(text.toBigDecimal())
                calcDialog.settings.isExpressionShown = true
                calcDialog.show((context as AppCompatActivity).supportFragmentManager, "")

            }

        }


        textView.doAfterTextChanged {
            text = textView.text.toString()
        }
    }

    private fun updateUnit(suffix: Map<String, Double>) {
        val items = arrayListOf<String>()
        suffix.forEach { i ->
            items.add(i.key)
        }
        val adapter: ArrayAdapter<String> =
            ArrayAdapter<String>(context, R.layout.simple_spinner_dropdown_item, items)
        planets_spinner.adapter = adapter
        planets_spinner.onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
            override fun onItemSelected(
                parent: AdapterView<*>?,
                view: View?,
                position: Int,
                id: Long
            ) {

                if (text.isNotEmpty()) {
                    p = suffix[items[position]]!!
                }


            }

            override fun onNothingSelected(parent: AdapterView<*>?) {

            }

        }
    }

    override fun onValueEntered(requestCode: Int, value: BigDecimal?) {
           textView.setText(value.toString())
           Toast.makeText(context, value.toString(), Toast.LENGTH_SHORT).show()

    }


}`

**Comment by maltaisn** [comment]
The callback must be implemented on a fragment or an activity, it won't work on a view. That's because the dialog has a way of finding both back through the fragment manager and the context, which isn't possible with a view.

I suggest you implement the callback in the activity/fragment containing this custom view, and then call another method on your custom view from there.
