### ISSUE TITLE
Missing CalcDialog class in JCenter / Bintray

### ISSUE THREAD

**Issue by mrollo** [maltaisn/calcdialoglib#4]
The aar published to jcenter has the CalcEraseButton class, but not the CalcDialog class.

**Comment by maltaisn** [comment]
Thanks, I fixed it. It was due to Proguard because I had enabled `minifyEnabled` to test it and forgot to disable it. Sorry for the inconvenience.

**Comment by mrollo** [comment]
Thank you @maltaisn ! Is it possible to release a new version to jcenter?
